[platformio]
default_envs = main

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico

framework = arduino

monitor_speed = 9600

lib_deps =
    PrivateLib=symlink://src/lib/private
    PublicLib=symlink://src/lib/public
    Wire
    SPI

build_flags =
    -Ofast
    -finline
    -funroll-loops

build_unflags =
    -O2

check_tool = cppcheck, clangtidy

[env:main]
build_src_filter = +<main.cpp>

; TESTS
; TESTS:PICO

[env:test_pico_helloworld]
build_src_filter = +<test/helloworld.cpp>

[env:test_pico_lidar0]
build_src_filter = +<test/lidar0.cpp>

[env:test_pico_lidar1]
build_src_filter = +<test/lidar1.cpp>

[env:test_pico_lidar5]
build_src_filter = +<test/lidar5.cpp>

[env:pico_tof_sense]
build_src_filter = +<test/tof_sense.cpp>

[env:pico_icm]
build_src_filter = +<test/gyro.cpp>

[env:pico_i2c_scan]
build_src_filter = +<test/i2c_scanner.cpp>

; TESTS:ESP32

[env:test_esp32_analogmux]
platform = espressif32
build_src_filter = +<test/analogmux.cpp>
; board = esp32dev
board = adafruit_feather_esp32s2
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:test_esp32_analogread]
platform = espressif32
build_src_filter = +<test/analogread.cpp>
board = adafruit_feather_esp32s2
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
