[platformio]
default_envs = main

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico

framework = arduino

monitor_speed = 115200

upload_protocol = picotool

lib_deps =
    PrivateLib=symlink://src/lib/private
    PublicLib=symlink://src/lib/public

build_flags =
    -Ofast
    -finline
    -funroll-loops

build_unflags =
    -O2

check_tool = cppcheck, clangtidy

[env:main]
build_src_filter = +<main.cpp>

; TESTS
; TESTS:PICO

[env:test_pico_helloworld]
build_src_filter = +<test/helloworld.cpp>

[env:pico_i2c_scan]
build_src_filter = +<test/i2c_scanner_pico.cpp>

; TESTS:ESP32

[env:esp32_analogread]
platform = espressif32
build_src_filter = +<test/analogread.cpp>
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
