[platformio]
default_envs = main

[env]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3

framework = arduino

monitor_speed = 115200

lib_deps =
    PrivateLib=symlink://src/lib/private
    PublicLib=symlink://src/lib/public
    Wire
    SPI

build_flags =
    ; -D CONFIG_ESP_CONSOLE_USB_CDC=y
    -D ARDUINO_USB_CDC_ON_BOOT=1

build_unflags =
    -O2

check_tool = cppcheck, clangtidy

[env:main]
build_src_filter = +<main.cpp>

; TESTS:ESP32

[env:esp32_camera_spi]
build_src_filter = +<test/camera_spi_test.cpp>

[env:esp32_camera_uart]
build_src_filter = +<test/camera_uart_test.cpp>

[env:esp32_uart_read]
build_src_filter = +<test/uart_read.cpp>

[env:esp32_i2c_comms]
build_src_filter = +<test/i2c_rw_esp.cpp>

[env:esp32_i2c_read]
build_src_filter = +<test/i2c_read_esp.cpp>

[env:esp32_i2c_write]
build_src_filter = +<test/i2c_write_esp.cpp>

[env:esp32_i2c_scan]
build_src_filter = +<test/i2c_scanner_esp.cpp>

[env:esp32_analogread]
build_src_filter = +<test/analogread.cpp>

[env:esp32_wifi]
build_src_filter = +<test/wifi_esp32.cpp>
lib_deps = 
    ESP Async Webserver
    ESP32Async/AsyncTCP
lib_ignore = AsyncTCP_RP2040W
