[platformio]
default_envs = main

[env]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3

framework = arduino

monitor_speed = 115200

lib_deps =
    PrivateLib=symlink://src/lib/private
    PublicLib=symlink://src/lib/public
    Wire
    SPI
    plerup/EspSoftwareSerial@^8.2.0
    ayushsharma82/WebSerial@^2.1.1
    ESP Async Webserver
    ESP32Async/AsyncTCP
lib_ignore = 
    AsyncTCP_RP2040W
    Async TCP
lib_ldf_mode = deep+

build_flags =
    -D CONFIG_ESP_CONSOLE_USB_CDC=y
    ; -D ARDUINO_USB_CDC_ON_BOOT=1

build_unflags =
    -O2

check_tool = cppcheck, clangtidy

[env:main]
build_src_filter = +<main.cpp>

; TESTS:ESP32

[env:new_main]
build_src_filter = +<main_new.cpp>

[env:esp32_attacker]
build_src_filter = +<attacker.cpp>

[env:esp32_defender]
build_src_filter = +<defender.cpp>

[env:esp32_ballhide2_test]
build_src_filter = +<test/ballhide2_test.cpp>

[env:esp32_balltrack]
build_src_filter = +<balltrack.cpp>

[env:esp32_camera_spi]
build_src_filter = +<test/camera_spi_test.cpp>

[env:esp32_camera_uart]
build_src_filter = +<test/camera_uart_test.cpp>

[env:esp32_uart_read]
build_src_filter = +<test/uart_read.cpp>

[env:esp32_i2c_comms]
build_src_filter = +<test/i2c_rw_esp.cpp>

[env:esp32_i2c_read]
build_src_filter = +<test/i2c_read_esp.cpp>

[env:esp32_i2c_write]
build_src_filter = +<test/i2c_write_esp.cpp>

[env:esp32_i2c_scan]
build_src_filter = +<test/i2c_scanner_esp.cpp>

[env:esp32_analogread]
build_src_filter = +<test/analogread.cpp>

[env:esp32_kicker]
build_src_filter = +<test/kicker.cpp>

[env:esp32_dribbler]
build_src_filter = +<test/dribbler.cpp>

[env:esp32_led_test]
build_src_filter = +<test/led_test.cpp>

[env:esp32_lookaheadtest]
build_src_filter = +<test/lookaheadtestnew.cpp>

[env:esp32_rotate_to_goal]
build_src_filter = +<test/rotate_to_goal.cpp>

[env:esp32_movement_test]
build_src_filter = +<test/movement.cpp>

[env:esp32_movetocentre]
build_src_filter = +<test/move_to_centre.cpp>

[env:esp32_wifi]
build_src_filter = +<test/wifi_esp32.cpp>

[env:esp32_bluetooth_sender]
build_src_filter = +<test/bluetooth_sender.cpp>

[env:esp32_bluetooth_receiver]
build_src_filter = +<test/bluetooth_receiver.cpp>

[env:esp32_get_mac_address]
build_src_filter = +<test/bluetooth_mac-address-getter.cpp>

[env:esp32_watchdog_test]
build_src_filter = +<test/esp_reset_test.cpp>

[env:esp32_software_serial]
build_src_filter = +<test/software_serial_read.cpp>

[env:esp32_webserial]
build_src_filter = +<test/esp32_webserial.cpp>
